### PR TITLE
Revised assignment for lesson 1 and assignment 2 finished

### PR DESCRIPTION
**Pull request by Luyao931213**
This is the revised version for lesson 1

### CODE REVIEW

**Comment by Luyao931213** [comment]
This pull request also include assignments  for lesson02

**Comment by Luyao931213** [comment]
Hello Luis, 

 I just want to thank you for giving me second change to revise my homework! I also appreciate your effort on grading them.

Have a nice day!
Luyao
发自我的 iPad

**Comment by ldconejo** [comment]
“ 发自我的iPad”！你说中文么？我也说一点中文 :-)

Anytime, one of the reasons we use Git for these courses is to give students a bit of a taste of what it is like to work in collaborative software development projects with version control tools, such as Git. In a project, you will often get feedback from reviewers and asked to submit an updated version, so that's what I do with all of my students: Provide feedback and ask them to submit additional pull requests up to the point at which the assignment meets all requirements.

Regards,

Luis

**Comment by Luyao931213** [comment]
Luis,
That's pretty cool to know that you can speak mandarin! If you want to practice sometime just email me back with the mandarin! I am free to chat any time!
希望您可以在以后的课程中给我更多的帮助！
谢谢！

路瑶
Luyao

发自我的 iPhone

**Pull request merged**
