### PR TITLE
submitting lesson_3 michael mcdonald

### PR DESCRIPTION
**Pull request by geekwriter2**
…st_price_equal(), line 80

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Michael,

For lesson 2, your code crashes while loading the CSV file:

```
$ python charges_calc.py -i source.json -o test.json
2020-08-25 18:53:16,748 charges_calc.py:108  INFO __name__
2020-08-25 18:53:16,748 charges_calc.py:31   INFO parse_cmd_arguments
2020-08-25 18:53:16,749 charges_calc.py:42   INFO load_rentals_file: filename =  source.json
2020-08-25 18:53:16,750 charges_calc.py:66   INFO calculate_additional_fields: my_data =        data
2020-08-25 18:53:16,755 charges_calc.py:79   INFO sqrt_total_price = (2017-03-22 00:00:00 - 2017-06-12 00:00:00) * 31 (-82) PRD80
2020-08-25 18:53:16,755 charges_calc.py:87   ERROR rental calculation error <class 'ValueError'> PRD80
Traceback (most recent call last):
  File "charges_calc.py", line 84, in calculate_additional_fields
    value['sqrt_total_price'] = math.sqrt(value['total_price'])
ValueError: math domain error
2020-08-25 18:53:16,755 charges_calc.py:79   INFO sqrt_total_price = (2018-09-30 00:00:00 - 2016-07-20 00:00:00) * 16 (802) PRD11
2020-08-25 18:53:16,756 charges_calc.py:79   INFO sqrt_total_price = (2017-06-04 00:00:00 - 2016-02-01 00:00:00) * 40 (489) PRD22
2020-08-25 18:53:16,756 charges_calc.py:79   INFO sqrt_total_price = (2017-12-07 00:00:00 - 2016-08-14 00:00:00) * 40 (480) PRD86
2020-08-25 18:53:16,756 charges_calc.py:79   INFO sqrt_total_price = (2018-11-23 00:00:00 - 2017-07-12 00:00:00) * 7 (499) PRD70
2020-08-25 18:53:16,756 charges_calc.py:102  INFO save_to_json: filename =      test.json, data =       data
ldconejo-mac09:lesson2 ldconejo$ python charges_calc.py -i source.json -o test.json -d 10
2020-08-25 18:53:55,994 charges_calc.py:108  INFO __name__
2020-08-25 18:53:55,994 charges_calc.py:31   INFO parse_cmd_arguments
```
Also, the requirements to implement different multiple debug levels, selected by the "-d" parameter, is not implemented.

-Luis

**Comment by ldconejo** [comment]
For assignment 3, implementation looks good, coverage is lower than the requirement (80% versus 90%). Try adding additional tests to get past 90%.

Regards,

Luis

**Comment by geekwriter2** [comment]
Luis,

I’ve redone lesson2 to handle the json files correctly in debugging and added a new function to handle the -d parameter. If I’ve pulled correctly the comment at the top should include v3.

https://github.com/UWPCE-PythonCert-ClassRepos/SP_Python220B_2019/pull/872

--
Michael

**Comment by geekwriter2** [comment]
Luis,

I’ve redone assignment 3 to include additional unittests. Coverage is now 91% with 24 tests.

--
Michael

**Pull request closed without merging**
