### PR TITLE
Lesson 6 Assignment

### PR DESCRIPTION
**Pull request by ganttArt**
Had some difficulties doing a $ git pull upstream master  on 6/11. I don't know what the difference would be but I'm guessing the request can't automatically merge because of something that had to do with that difficulty.

Most importantly, the code for Lesson 6's assignment is included. Thanks!

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Chris,

This pull request includes modified files from another student's folder:

students/chris_lombardi/Lesson04/assignment/basic_operations.py

Could you remove this file and submit another pull request? Make sure only files within your _students/christopher_gantt_ folder are included.

Thanks,

Luis

**Comment by ganttArt** [comment]
Luis,

I'm having a lot of issues getting this to work. Could I possibly create a
new fork and create a pull request from that?

-Chris

**Comment by ldconejo** [comment]
Hi Chris,

Yes, it's a bit of a nuclear solution, but it would work, as your starting point would be latest version of the course repository.

Since the conflict is caused by a single file, you could also try deleting that file (students/chris_lombardi/Lesson04/assignment/basic_operations.py) in your current fork and see if the _$ git pull upstream master_ now completes successfully. 

Regards,

Luis

**Comment by ganttArt** [comment]
Luis,

I got things sorted out with git and have submitted a pull request for
lesson 6. Thank you again for your help through this.

-Chris

**Comment by ganttArt** [comment]
https://github.com/UWPCE-PythonCert-ClassRepos/SP_Python220B_2019/pull/116

**Pull request closed without merging**
