### PR TITLE
Pull req for py220

### PR DESCRIPTION
**Pull request by tsulgrove**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Thomas,

Lesson 01 looks good, with the file with lowest coverage (_main.py_) at 94%, which surpasses the requirements. Pylint is reporting some minor indentation issues which should be easy to fix:

```
$ python -m pylint inventory_management/
************* Module main
inventory_management/main.py:58:0: C0330: Wrong continued indentation (remove 16 spaces).
                                             item_price, item_rental_price,
                             |               ^ (bad-continuation)
inventory_management/main.py:59:0: C0330: Wrong continued indentation (remove 16 spaces).
                                             item_material, item_size)
                             |               ^ (bad-continuation)
inventory_management/main.py:66:0: C0330: Wrong continued indentation (remove 26 spaces).
                                                                    item_price, item_rental_price,
                                          |                         ^ (bad-continuation)
inventory_management/main.py:67:0: C0330: Wrong continued indentation (remove 26 spaces).
                                                                    item_brand, item_voltage)
                                          |                         ^ (bad-continuation)
inventory_management/main.py:70:0: C0330: Wrong continued indentation (remove 16 spaces).
                                                 item_price, item_rental_price)
                                 |               ^ (bad-continuation)

------------------------------------------------------------------
Your code has been rated at 9.37/10 (previous run: 9.17/10, +0.20)
```

What I do is that I grade the assignment as it is and the update the grade once you submit a revised version.

Regards,

Luis

**Comment by ldconejo** [comment]
Assignment two looks good.

**Comment by ldconejo** [comment]
For lesson 3, your _test_basic_operations.py_ throws the following error:

```
======================================================================
ERROR: test_update_customer (test_basic_operations.TestBasicOps)
Test the ability to ability to update a customer
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ldconejo/Documents/UW/SP_Python220B_2019/SP_Python220B_2019/students/thomas_sulgrove/lesson03/assignment/tests/test_basic_operations.py", line 62, in test_update_customer
    database_setup()
  File "/Users/ldconejo/Documents/UW/SP_Python220B_2019/SP_Python220B_2019/students/thomas_sulgrove/lesson03/assignment/tests/test_basic_operations.py", line 20, in database_setup
    database.drop_tables([Customer])
NameError: name 'database' is not defined
```

It's a very simple issue, one that is fixed, your coverage is below the required 90%, so make sure you add additional tests to get to 90% or higher.

**Comment by ldconejo** [comment]
Lesson 4 inherited the same issues from lesson 1.

**Comment by ldconejo** [comment]
Hi Thomas,

I don't see a submission for lessons 6 & 8 on the course website, so I'm assuming those assignments are not yet ready for review.

Regards,

Luis

**Comment by ldconejo** [comment]
Assignment 7 is missing _database.py_

**Comment by tsulgrove** [comment]
Hey Luis,

Cant submit code on that one.. Thought it might need the previous courses
in for it.

Thanks for the feedback!
Tom

snip:
[image: image.png]

**Comment by ldconejo** [comment]
Hi Thomas,

For lesson 6, do you mean you couldn't find the required files? They're here:

https://github.com/UWPCE-PythonCert-ClassRepos/SP_Python220B_2019/tree/master/lessons/lesson06/assignment

Let me know if this helps.

Thanks,

Luis

**Comment by ldconejo** [comment]
For lesson 10, make sure you include a file called _timings.txt_ with the collected timing data. Other than that, your implementation looks good.

**Comment by ldconejo** [comment]
Hi Thomas,

Huge pull request, it looks like your submitted almost the entire course in a single pull request :-) 

Anyway, please take a look at the comments from the different assignments and submit the corresponding updates (it's easier if you do a pull request for each assignment as you make the necessary changes).

Regards,

Luis

**Comment by tsulgrove** [comment]
Luis,

Nope, there isn't a button to attach zip file with code for some reason on
the submission screen. I'll check back in morning after all this is in and
see if it shows.

Thanks,
Tom

**Comment by ldconejo** [comment]
Don't worry about attaching code on the submission screen. I review code exclusively on Github. On the course website, just include a link to the pull request that has the corresponding files. I just closed the existing pull request, so go ahead an open a new one with any updated files (or in this case, for review on assignment 6).

**Pull request closed without merging**
