### PR TITLE
L02 Assignment

### PR DESCRIPTION
**Pull request by pbehrend**
Added logging and try-except to catch negative or empty values in json file to enable it to run properly.

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Philip,

For lesson 1, the _inventory_management_ folder is missing the following files:

_electric_applicances_class.py_
_furniture_class.py_
_inventory_class.py_

These need to be included and tested with the existent structure, as in many cases you will need to do unit tested on projects for which you cannot introduce major changes to the existing code and file structure.

Also, make sure you remove non-related files from the _inventory_management_ folder (_mock_tutorial.py_, _patch_tutorial.py_, etc.).

-Luis

**Comment by ldconejo** [comment]
Also for lesson 1, run a coverage analysis (using the Python _coverage_ module) and make sure each individual file inside of _inventory_management_ is at 90% or higher coverage.

Finally, make sure you also run Pylint on those files and address any PEP8 compliance warnings that are raised.

**Comment by ldconejo** [comment]
For lesson 2, you need to implement a _-d / --debug_ input parameter to select different levels of logging (0-no log, 1-errors only, 2-errors and warnings, 3-errors/warnings/debug messages). Make sure your code will also reject invalid debug levels (ex. --debug 10).

Also in this case, make sure you run Pylint and address all PEP8 compliance issues until you get a 10 out of 10 rating on the code (you can use a custom .pylintrc and/or Pylint disable statements in cases in which you think a particular PEP8 rule should not apply to your code).

Regards,

Luis

**Comment by pbehrend** [comment]
Hi Luis, I've made all but one of the changes you specified. I'm having
issues testing the Main Menu while loop. All other lines in the file have
been tested, but that's not enough to get us to 90% coverage. Whenever I
run *test_main_menu *from the command line, I get an endless loop - do you
have any thoughts on how to fix this?
(Troublesome test file attached)

Thanks,
Philip

**Comment by ldconejo** [comment]
Hi Philip,

Could you open a new pull request with the latest status of your code (include all files)? I'll take a look at coverage and the issue you're having with Main Menu.

Regards,

Luis

**Comment by pbehrend** [comment]
Will do, thank you

https://github.com/UWPCE-PythonCert-ClassRepos/SP_Python220B_2019/pull/351

**Pull request closed without merging**
