### PR TITLE
working on test_unit

### PR DESCRIPTION
**Pull request by LAFiorizarry**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Laura,

I looked at your code, but it seems _test_add_new_item_ within _test_unit.py_ is already running correctly. Even, more, I ran a coverage analysis, _add_new_item_ is covered by your current implementation. 

Could you give me some more details as to when do you get the error message you mentioned?

Thanks,

Luis

**Comment by LAFiorizarry** [comment]
Sorry, I forgot that I had defined FULL_INVENTORY at the beginning of
main.py, but I wasn't sure if that should be necessary. If I don't put
FULL_INVENTORY={} in main, then I get an error when I run test_unit. So is
it ok to add to the main.py file or should I just be creating the tests?
Laura

**Comment by ldconejo** [comment]
Hi Laura,

Yes, that should be fine, as long as coverage and testing are achieved.

-Luis

**Comment by ldconejo** [comment]
Closing this pull request. Please enter a new submission once the assignment is ready for review (or if/when additional questions come up ;-) ).

-Luis

**Pull request closed without merging**
