### PR TITLE
Changes to lesson2

### PR DESCRIPTION
**Pull request by ericae14**
Made the changes listed below
Hi Erica,
Implementation looks good. A couple of things to change:
1.	Your code run without any arguments, it should instead error out, telling the users which parameters are required / optional.
2.	init_logger() takes one parameter, but doesn't use it (it calls args.debug directly instead), please modify so that args.debug is passed to the function (and used).
3.	Run Pylint on your code and correct the issues detected until you get 10 out 10 grade (currently, your code is at 3.85/10). Note that Pylint allows you to use comments in code to disable some warnings. If you decide to use this feature, please indicate which warnings you're disabling and the reason.

### CODE REVIEW

**Comment by ericae14** [comment]
Closing request. updated lesson 2 and lesson 3 have been combined into one pull.

**Comment by ericae14** [comment]
Couldn't see how to split lesson 2 and lesson 3 into separate pull requests.

**Comment by ldconejo** [comment]
Hi Erica,

It's ok about the single pull request. That's how it works for a regular project. Developers will add to their pull requests as they keep making progress with their code, each update being merged into a single pull request (if one is already open).

Your changes for lesson 2 look good, I have already updated the grade accordingly. For lesson 3, you have submitted the assignment on the course website, so I cannot grade it yet. I will close this pull request for now, while you do the submission. Feel free to just reopen this pull request once the submission for assignment 3 on the course website is ready.

Keep up the good work!

-Luis

**Comment by ericae14** [comment]
Reopening pull request

**Pull request closed without merging**
