### PR TITLE
First and second lesson submissions

### PR DESCRIPTION
**Pull request by nubber7**
Submission of PDB text file and updates to the file with logging details.
```
➜  lesson01 git:(master) ✗ ls
__pycache__            inventory_management   test_unit.py.gz
assignment1.txt.gz     test_integration.py.gz tests
➜  lesson01 git:(master) ✗
```

```
➜  lesson02 git:(master) ✗ ls
2019-05-19_charges_calc.log charges_calc.py             out.json
charges_calc.log            charges_calc_pdb.txt        source.json
```

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Ramakanth,

For lesson 1, coverage of _main.py_ is very low at 56%. Try to add additional code to your unit testing to bring it to 90%+. For Pylint, the following warning currently shows up:

************* Module inventory_management.market_prices
inventory_management/market_prices.py:1:0: R0801: Similar lines in 3 files
==inventory_management.electric_appliances_class:19
==inventory_management.furniture_class:16
==inventory_management.inventory_class:13
    def return_as_dictionary(self):
        """Function to store inventory as a data dictionary"""
        output_dict = dict()
        output_dict['product_code'] = self.product_code
        output_dict['description'] = self.description
        output_dict['market_price'] = self.market_price
        output_dict['rental_price'] = self.rental_price (duplicate-code)

-------------------------------------------------------------------
Your code has been rated at 9.90/10 (previous run: 10.00/10, -0.10)

Submit a new pull request once this has been fixed.

Regards,

Luis

**Comment by ldconejo** [comment]
For lesson 2, please run Pylint on your code and make sure all warnings are fixed to the point where Pylint grades it with 10 out of 10. You may use selective rule disabling, for example:

`# pylint: disable=W1202`

If you do so, please indicate why the warning cannot be fixed and instead should be disabled.

Regards,

Luis

**Comment by nubber7** [comment]
```
Corrected
➜  lesson02 git:(master) ✗ python -m pylint charges_calc.py
Using config file /Users/guntur/.pylintrc

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

**Comment by nubber7** [comment]
Corrected the duplicate code to inherit from super class.
```
       output_dict['product_code'] = self.product_code
        output_dict['description'] = self.description
        output_dict['market_price'] = self.market_price
        output_dict['rental_price'] = self.rental_price
```

**Pull request closed without merging**
