### PR TITLE
submission of L05

### PR DESCRIPTION
**Pull request by cjfortu**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Clemente,

Were you able to run your tests without failures? In my run, two of the tests are failing:

```
======================================================================
FAIL: test_clear_data (test_database.FunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1342, in patched
    return func(*newargs, **newkeywargs)
  File "/Users/ldconejo/Documents/UW/SP_Python220B_2019/SP_Python220B_2019/students/cjfortu/L05/assignment/tests/test_database.py", line 102, in test_clear_data
    self.assertEqual(mock_stdout.getvalue(), """valid rows/documents = (8, 5, 15)   invalid rows/documents(blank entries aside from end_date) = (1, 0, 1)
AssertionError: "vali[100 chars])\n['HPNorton', 'Inventory', 'admin', 'config'[49 chars]']\n" != "vali[100 chars])\n['admin', 'config', 'local']\n"
  valid rows/documents = (8, 5, 15)   invalid rows/documents(blank entries aside from end_date) = (1, 0, 1)
- ['HPNorton', 'Inventory', 'admin', 'config', 'hp_norton', 'hpn', 'lesson05', 'local', 'media']
+ ['admin', 'config', 'local']


======================================================================
FAIL: test_main_menu_3 (test_database.FunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 1342, in patched
    return func(*newargs, **newkeywargs)
  File "/Users/ldconejo/Documents/UW/SP_Python220B_2019/SP_Python220B_2019/students/cjfortu/L05/assignment/tests/test_database.py", line 171, in test_main_menu_3
    self.assertEqual(mock_stdout.getvalue(), """Please choose from the following:
AssertionError: "Plea[232 chars]t\n['HPNorton', 'Inventory', 'admin', 'config'[49 chars]']\n" != "Plea[232 chars]t\n['admin', 'config', 'local']\n"
  Please choose from the following:
                '1' - Print database
                '2' - Load data
                '3' - Clear data
                '4' - Show available products
                '5' - Show rentals
                'q' - Quit
- ['HPNorton', 'Inventory', 'admin', 'config', 'hp_norton', 'hpn', 'lesson05', 'local', 'media']
+ ['admin', 'config', 'local']
```

**Comment by ldconejo** [comment]
Closing this pull request for now.

**Comment by cjfortu** [comment]
Thanks for the feedback, Luis!

Strange, I copied/pasted the raw text from my submissions on the Github website, and ran them.  All passes.  Could this be a windows/mac issue?  

I can do a Zoom meet again to show you my tests passing, if you prefer.


VR

Clemente

**Comment by cjfortu** [comment]
Wait, I think I can improve the tests.

Currently, the ones failing on your end… they assert that the remaining databases are the three I listed.  This is different than asserting that the products database was deleted.  So on your machine, my tests read all databases still on yours.  I’ll modify this and resubmit.

**Comment by cjfortu** [comment]
https://github.com/UWPCE-PythonCert-ClassRepos/SP_Python220B_2019/pull/652 <https://github.com/UWPCE-PythonCert-ClassRepos/SP_Python220B_2019/pull/652>

This should work.  Thanks again!

**Pull request closed without merging**
