### PR TITLE
submitting lesson2 assignment michael_mcdonald

### PR DESCRIPTION
**Pull request by geekwriter2**

### CODE REVIEW

**Comment by geekwriter2** [comment]
submitting lesson2 assignment michael_mcdonald

**Comment by ldconejo** [comment]
Hi Michael,

Please make sure both your unit and integration tests are running successfully and open a new pull request. Currently, there is at least one error in _test_get_latest_price_equal()_ that would make that test fail. Other than that, this submissions looks good. Also remember to submit on the course website, so that I can grade your assignment (at any point, if you get less than the full grade, you can always fix any errors / missing requirements and submit a new pull request to get to the full grade).

Please let me know if you have any questions.

-Luis

**Comment by geekwriter2** [comment]
ty - I'll take a look at test_get_latest_price_equal()

**Comment by geekwriter2** [comment]
Luis, thanks much,

The error is corrected. I updated the import statements throughout the lesson so also resubmitted the supporting files.

https://github.com/UWPCE-PythonCert-ClassRepos/SP_Python220B_2019/pull/866

--
Michael

**Pull request closed without merging**
